version: 0.2
phases:
  install:
    runtime-versions:
      java: corretto17  # Amazon Corretto is a no-cost, multiplatform, production-ready 
                        # distribution of the Open Java Development Kit (OpenJDK)
